apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
  labels:
    app: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
    spec:
      containers:
      - name: alpha
        image: rnarainsamy3/alpha:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: alpha-service
spec:
  selector:
    app: alpha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
